services:
  server:
    build: .
    container_name: tuj_auth_server
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    env_file:
      - .env
    networks:
      - tuj-network

  db:
    image: mysql:8.0
    container_name: tuj_auth_db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - tuj-network

networks:
  tuj-network:
    driver: bridge

volumes:
  db_data:
